table _Measures
	lineageTag: 68253867-a07a-4580-a050-238c2bf45128

	measure lineChart_BearishCandle =
			
			VAR _Diff = ABS(MAXX(factStocks, [Close]-[Open]))
			RETURN
			        IF(MAXX(factStocks, [Close]-[Open]) < 0, _Diff)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 73c3290b-f4cc-48d0-8b96-af4298e9224f

	measure lineChart_BullishCandle =
			
			VAR _Diff = ABS(MAXX(factStocks, [Close]-[Open]))
			RETURN
			            IF(MAXX(factStocks, [Close]-[Open]) > 0, _Diff)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b2019628-918f-43f3-8c32-281143daab0e

	measure lineChart_High = AVERAGE(factStocks[High])
		formatString: #,0.00
		lineageTag: 4bad6dbe-1892-47ab-9aaa-1431da9d9b1c

	measure lineChart_Low = AVERAGE(factStocks[Low])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bd414f93-c14e-4dc1-9f26-0105dcdfbd81

	measure MaxY = ```
			MAX(factStocks[Close]) + 5 
			```
		lineageTag: a157ae4e-47a3-4b46-bbe7-72a25a6a6a59

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MinY = MIN(factStocks[Close]) - 5
		lineageTag: cefb0330-a88b-4274-9c67-844a34dbb656

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure HighDistance =
			
			VAR _MaxValue = IF(MAXX(factStocks, [Close]-[Open]) > 0, MAXX(factStocks, [Close]), MAXX(factStocks, [Open]))
			VAR _High = MAXX(factStocks, [High])
			RETURN
			ABS(_High - _MaxValue) * - 1 -- I multiply by -1 to reverse the direction (Up to Down)
		lineageTag: 7a4d1a28-4784-4f16-aad2-4af4ec975130

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure lineChart_LowDistance =
			
			VAR _MinValue = IF(MAXX(factStocks, [Close]-[Open]) < 0, MAXX(factStocks, [Close]), MAXX(factStocks, [Open]))
			VAR _Low = MAXX(factStocks, [Low])
			RETURN
			ABS( _Low - _MinValue )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: edfb8ed4-43ca-4fed-86f6-977af5e7ce33

	measure BeginingPeriodPrice = ```
			
			VAR _StartDate = CALCULATE(MIN(dimPeriod[StartDate]), ALLSELECTED(dimPeriod))
			VAR _Price =
			    CALCULATE(
			        MAX(factStocks[Close]),
			        factStocks[Date] = _StartDate
			    )
			VAR _NextDay =
			    CALCULATE(
			        MIN(factStocks[Date]),
			        factStocks[Date] > _StartDate
			    )
			VAR _AdjustedPrice =
			    CALCULATE(
			        MAX(factStocks[Close]),
			        factStocks[Date] = _NextDay
			    )
			RETURN
			    IF(NOT ISBLANK(_Price), _Price, _AdjustedPrice)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2e534648-d856-482c-8201-aef31a6f0a6c

	measure DateFilter = IF( MAX(factStocks[Date]) >= MAX( dimPeriod[StartDate] ), 1 )
		formatString: 0
		lineageTag: 0906059c-f17d-4293-93bc-dade05489ef5

	measure 'lineChart_Moving Average' = ```
			
			VAR _Period = SELECTEDVALUE(_tParameter[NbOfDays], 10)  -- Default to 7 days if no value selected
			VAR _MaxDate = LASTDATE(factStocks[Date])  -- Get the latest date in the current context
			VAR _StartDate = _MaxDate - _Period + 1  -- Calculate the start date of the moving window
			
			VAR _Numerator = CALCULATE(
			    SUM(factStocks[Close]), 
			    factStocks[Date] >= _StartDate && factStocks[Date] <= _MaxDate  -- Filter for the current period
			)
			
			VAR _Denominator = CALCULATE(
			    COUNT(factStocks[Date]), 
			    factStocks[Date] >= _StartDate && factStocks[Date] <= _MaxDate  -- Filter for the current period
			)
			
			RETURN 
			IF(_Denominator > 0, DIVIDE(_Numerator, _Denominator), BLANK())  -- Return the average or blank if no data
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c95e8a44-9c15-43eb-94b2-f0f7a5806d61

	measure 'Variation %' =
			
			VAR _variation = (DIVIDE([LastClosePrice], [BeginingPeriodPrice]) - 1)*100
			
			-- Format the scaled variation
			VAR _variationFormat = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(_Variation, "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			
			-- Add the up or down arrow
			VAR _Arrow = IF(_variation > 0, UNICHAR(129033) & " ", UNICHAR(129035)) & " "
			
			RETURN
			    _Arrow & _variationFormat & "%"
		lineageTag: f8bd3b3d-248d-4011-b302-df196c66e07a

	measure 'Variation Curr Vs Prec' = ```
			
			
			VAR _PrevClose  = AVERAGE( factStocks[PrevClose] )
			VAR _CurrClose = AVERAGE( factStocks[Close] )
			VAR _Variation = DIVIDE( _CurrClose , _PrevClose ) - 1
			RETURN
			 _Variation 
			```
		lineageTag: 4780cb27-9d72-4e34-9bce-1ac5ea5b16dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variation Indicator' =
			
			VAR _Variation = DIVIDE([LastClosePrice], [BeginingPeriodPrice]) - 1
			RETURN
			IF( _Variation >= 0, 0, 1 )
		formatString: 0
		lineageTag: d942b59a-f2b4-4bfc-b8c0-b9124d37170c

	measure portofolio_#1_At_Close = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])
			VAR _FirstCompany =
			    MAXX(
			        TOPN(1, _SelectedValues, dimLogo[Company], ASC),
			        dimLogo[Company]
			    )
			VAR _FilteredSymbol =
			    MAXX(
			        FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			        dimLogo[Symbol]
			    )
			VAR _MaxDate =
			    CALCULATE(
			        MAX(factStocks[Date]),
			        FILTER(factStocks, factStocks[Symbol] = _FilteredSymbol)
			    )
			VAR NewLine = UNICHAR(10)
			RETURN
			    IF(
			        COUNTROWS(_SelectedValues) >= 1 && NOT ISBLANK(_MaxDate),
			        "🕒 Closed at" & NewLine & FORMAT(_MaxDate, "dddd, d mmmm yyyy"),
			        BLANK()
			    )
			
			```
		lineageTag: e8dd6baa-1172-41d9-9fea-332cb5c18ab7

	measure 'barChart_Green Volume' = ```
			
			VAR _PrevClose  = CALCULATE( AVERAGE(factStocks[Close]),
			                            OFFSET(-1, 
			                                    ALLSELECTED (factStocks[Date],factStocks[symbol] ),
			                                    ORDERBY(factStocks[Date] ),
			                                    PARTITIONBY(factStocks[symbol] ) 
			                                  )
			                                )
			VAR _CurrClose = AVERAGE(factStocks[Close] )
			VAR _Volume = AVERAGE(factStocks[Volume] )
			RETURN
			IF( _CurrClose > _PrevClose, _Volume)
			```
		lineageTag: baead23e-c210-443a-aeaf-e7e2baf4eb95

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'barChart_Red Volume' = ```
			
			VAR _PrevClose  = CALCULATE( AVERAGE(factStocks[Close]),
			                            OFFSET(-1, 
			                                    ALLSELECTED (factStocks[Date],factStocks[symbol] ),
			                                    ORDERBY(factStocks[Date]),
			                                    PARTITIONBY(factStocks[symbol] ) 
			                                  )
			                                )
			VAR _CurrClose = AVERAGE(factStocks[Close])
			VAR _Volume = AVERAGE(factStocks[Volume])
			RETURN
			IF( _CurrClose < _PrevClose, _Volume)
			```
		lineageTag: ea9e57a8-1589-4d83-af4e-3695682a86d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MaxVolume = ```
			MAX(factStocks[Volume]) 
			```
		lineageTag: 54c00824-7db3-4d21-8068-83f42e604fa4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ToolTips = ```
			
			VAR _Date = FORMAT(MAX(factStocks[Date]), "d MMMM yyyy", "en-CA")
			VAR _OpenText = "Open"
			VAR _HighText = "High"
			VAR _LowText = "Low"
			VAR _CloseText = "Close"
			VAR _VolumeText = "Volume"
			VAR _PercChangeText = "% Change"
			
			VAR _CurrencySymbol = CALCULATE(
			        SELECTEDVALUE(dimCurrencySymbol[Currency Symbol]),
			        TREATAS(VALUES(dimMeta[Currency]), dimCurrencySymbol[Currency])
			    )
			
			VAR _OpenFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(MAX(factStocks[Open]), "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			VAR _HighFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(MAX(factStocks[High]), "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			VAR _LowFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(MAX(factStocks[Low]), "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			VAR _CloseFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(MAX(factStocks[Close]), "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			
			-- Format Open, High, Low, Close with the currency symbol on the right
			VAR _Open = _OpenFormated & _CurrencySymbol
			VAR _High = _HighFormated & _CurrencySymbol
			VAR _Low = _LowFormated & _CurrencySymbol
			VAR _Close = _CloseFormated & _CurrencySymbol
			
			//VAR _VolumeFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(MAX(factStocks[Volume]), "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			VAR _VariationFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([Variation Curr Vs Prec] * 100, "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			
			-- Format Volume and Variation as before
			VAR _Volume = FORMAT(MAX(factStocks[Volume]), "0,,.00M")
			VAR _Variation = _VariationFormated & "%"
			
			-- Define layout variables with reduced space
			VAR _Espace = "‎ " -- white space
			VAR _BeforeEspaceNumber = 11 -- Reduced space before the value
			VAR _Lenght = 6  -- Reduced length to bring values closer
			VAR _TotalLenght = _BeforeEspaceNumber + _Lenght
			
			-- Correct the calculation for the dashed line length
			VAR _LenghtOfDashLine = 
			    IF(
			        LEN(_CurrencySymbol) > 1, 
			        REPT("-", ROUND(_TotalLenght + 4, 0)),  -- Ensure the length is a valid integer
			        REPT("-", _TotalLenght + 1)
			    ) 
			
			VAR _CenteredText = ROUND(DIVIDE(_TotalLenght - LEN(_Date), 2), 0)
			
			-- Adjust for multibyte currency symbols and avoid negative values
			VAR _OpenDisplayLength = LEN(FORMAT(MAX(factStocks[Open]), "0.00")) + LEN(_CurrencySymbol)
			VAR _HighDisplayLength = LEN(FORMAT(MAX(factStocks[High]), "0.00")) + LEN(_CurrencySymbol)
			VAR _LowDisplayLength = LEN(FORMAT(MAX(factStocks[Low]), "0.00")) + LEN(_CurrencySymbol)
			VAR _CloseDisplayLength = LEN(FORMAT(MAX(factStocks[Close]), "0.00")) + LEN(_CurrencySymbol)
			VAR _VolumeDisplayLength = LEN(FORMAT(MAX(factStocks[Volume]), "0,,.00M"))
			VAR _VariationDisplayLength = LEN(FORMAT([Variation Curr Vs Prec], "0.00%"))
			
			-- Return the tooltip text with the currency symbol on the right
			RETURN
			_LenghtOfDashLine & UNICHAR(10) & REPT(_Espace, _CenteredText) & _Date & UNICHAR(10) & _LenghtOfDashLine & UNICHAR(10) &
			_OpenText & REPT(_Espace, MAX(0, _BeforeEspaceNumber - LEN(_OpenText))) & REPT(_Espace, MAX(0, _Lenght - _OpenDisplayLength)) & _Open & UNICHAR(10) &
			_HighText & REPT(_Espace, MAX(0, _BeforeEspaceNumber - LEN(_HighText))) & REPT(_Espace, MAX(0, _Lenght - _HighDisplayLength)) & _High & UNICHAR(10) &
			_LowText & REPT(_Espace, MAX(0, _BeforeEspaceNumber - LEN(_LowText))) & REPT(_Espace, MAX(0, _Lenght - _LowDisplayLength)) & _Low & UNICHAR(10) &
			_CloseText & REPT(_Espace, MAX(0, _BeforeEspaceNumber - LEN(_CloseText))) & REPT(_Espace, MAX(0, _Lenght - _CloseDisplayLength)) & _Close & UNICHAR(10) &
			_VolumeText & REPT(_Espace, MAX(0, _BeforeEspaceNumber - LEN(_VolumeText))) & REPT(_Espace, MAX(0, _Lenght - _VolumeDisplayLength)) & _Volume & UNICHAR(10) &
			_PercChangeText & REPT(_Espace, MAX(0, _BeforeEspaceNumber - LEN(_PercChangeText))) & REPT(_Espace, MAX(0, _Lenght - _VariationDisplayLength)) & _Variation
			
			```
		lineageTag: feb3128c-ad65-4435-8fea-604e1cb0c27c

	measure LastClosePrice = ```
			
			VAR _EndDate = CALCULATE(MAX(dimPeriod[EndDate]), ALLSELECTED(dimPeriod))
			VAR _LastDate =
			    MAXX(
			        FILTER(
			            factStocks,
			            factStocks[Date] <= _EndDate
			        ),
			        factStocks[Date]
			    )
			RETURN
			    IF(
			        ISBLANK(_LastDate),
			        BLANK(),  // Return BLANK if no valid _LastDate is found
			        CALCULATE(
			            MAX(factStocks[Close]),
			            factStocks[Date] = _LastDate
			        )
			    )
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5ed3900c-23f5-4adc-b7d2-11fe1fa620d4

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Variation #' = ```
			
			VAR _Delta = [LastClosePrice] - [BeginingPeriodPrice]
			VAR _deltaFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(_Delta, "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			VAR _Currency = 
			    CALCULATE(
			        SELECTEDVALUE(dimCurrencySymbol[Currency Symbol]),
			        TREATAS(VALUES(dimMeta[Currency]), dimCurrencySymbol[Currency])
			    )
			VAR _Period = MAX(dimPeriod[Period])
			VAR _Arrow = 
			    IF(
			        _Delta > 0,
			        UNICHAR(129033), 
			        UNICHAR(129035)
			    ) & " "
			RETURN
			    _Arrow & _deltaFormated & _Currency & " | △(" & _Period & ")"
			```
		lineageTag: e4834ebc-bf0c-45ce-8894-a228b4c78c8b

	measure 'Exponential Moving Average' = ```
			
			VAR _Period = SELECTEDVALUE(_tParameter[NbOfDays], 10)  -- Default period of 10 if not selected
			VAR _K = 2 / (_Period + 1)  -- Smoothing factor
			VAR _MaxDate = MAX(factStocks[Date])  -- Latest date in the current context
			VAR _DatesInPeriod = DATESINPERIOD(factStocks[Date], _MaxDate, -_Period, DAY)
			
			-- Step 1: Calculate Initial EMA as SMA of the first period
			VAR _InitialEMA = 
			    CALCULATE(
			        AVERAGE(factStocks[Close]),
			        _DatesInPeriod
			    )
			
			-- Step 2: Build Weighted Sum and Total Weight
			VAR _WeightedTable =
			    ADDCOLUMNS(
			        _DatesInPeriod,
			        "Close", CALCULATE(SUM(factStocks[Close])),
			        "Weight", _K * POWER(1 - _K, DATEDIFF(factStocks[Date], _MaxDate, DAY))
			    )
			
			VAR _WeightedSum = SUMX(_WeightedTable, [Close] * [Weight])
			VAR _TotalWeight = SUMX(_WeightedTable, [Weight])
			
			-- Step 3: Calculate EMA
			VAR _EMA = DIVIDE(_WeightedSum, _TotalWeight)
			
			RETURN
			    IF(ISBLANK(_InitialEMA), BLANK(), _EMA)
			```
		formatString: "CHF"\ #,0.###############;"CHF"-#,0.###############;"CHF"\ #,0.###############
		lineageTag: 308ea926-0875-49ed-8c66-d80d7c092ca4

		annotation PBI_FormatHint = {"currencyCulture":"en-CH"}

	measure 'lineChart_Lower Band' = ```
			
			VAR _Period = SELECTEDVALUE(_tParameter[NbOfDays])
			VAR _LastDate = LASTDATE(factStocks[Date])
			VAR _DatesInPeriod = DATESINPERIOD(factStocks[Date], _LastDate, -_Period, DAY)
			VAR _SMA = '_Measures'[lineChart_Moving Average]
			VAR _StdDev = 
			    STDEVX.P(
			        _DatesInPeriod,
			        CALCULATE(SUM(factStocks[Close]))
			    )
			
			RETURN
			    _SMA - (2 * _StdDev)
			
			```
		formatString: "CHF"\ #,0.###############;"CHF"-#,0.###############;"CHF"\ #,0.###############
		lineageTag: 3c4acb54-69e9-453f-88e7-362ae243bfee

		annotation PBI_FormatHint = {"currencyCulture":"en-CH"}

	measure 'lineChart_Upper Band' = ```
			
			VAR _Period = SELECTEDVALUE(_tParameter[NbOfDays])
			VAR _LastDate = LASTDATE(factStocks[Date])
			VAR _DatesInPeriod = DATESINPERIOD(factStocks[Date], _LastDate, -_Period, DAY)
			VAR _SMA = '_Measures'[lineChart_Moving Average]
			VAR _StdDev = 
			    STDEVX.P(
			        _DatesInPeriod,
			        CALCULATE(SUM(factStocks[Close]))
			    )
			
			RETURN
			    _SMA + (2 * _StdDev)
			
			```
		formatString: "CHF"\ #,0.###############;"CHF"-#,0.###############;"CHF"\ #,0.###############
		lineageTag: d2cdbe67-48d6-4277-825c-784819eae0a8

		annotation PBI_FormatHint = {"currencyCulture":"en-CH"}

	measure 'Total Close Price' = SUM(factStocks[Close])
		formatString: "CHF"\ #,0.###############;"CHF"-#,0.###############;"CHF"\ #,0.###############
		lineageTag: 2868d987-66c9-4584-a7d7-e74abe659ba5

		annotation PBI_FormatHint = {"currencyCulture":"en-CH"}

	measure Slope =
			
			VAR Known =
			    FILTER(
			        SELECTCOLUMNS(
			            ALLSELECTED('dimCalendar'[Date]),
			            "Known[X]", 'dimCalendar'[Date],
			            "Known[Y]", [Total Close Price]
			        ),
			        AND(
			            NOT(ISBLANK(Known[X])),
			            NOT(ISBLANK(Known[Y]))
			        )
			    )
			VAR Count_Items =
			    COUNTROWS(Known)
			VAR Sum_X =
			    SUMX(Known, Known[X])
			VAR Sum_X2 =
			    SUMX(Known, Known[X] ^ 2)
			VAR Sum_Y =
			    SUMX(Known, Known[Y])
			VAR Sum_XY =
			    SUMX(Known, Known[X] * Known[Y])
			VAR Average_X =
			    AVERAGEX(Known, Known[X])
			VAR Average_Y =
			    AVERAGEX(Known, Known[Y])
			RETURN
			    DIVIDE(
			        Count_Items * Sum_XY - Sum_X * Sum_Y,
			        Count_Items * Sum_X2 - Sum_X ^ 2
			    )
		formatString: "CHF"\ #,0.###############;"CHF"-#,0.###############;"CHF"\ #,0.###############
		lineageTag: 29b3d254-33c0-472b-8c00-9ab2da45e03a

		annotation PBI_FormatHint = {"currencyCulture":"en-CH"}

	measure 'Last Close Price Blank' = CALCULATE(LASTNONBLANKVALUE(factStocks[Date],[Total Close Price]),ALLSELECTED(factStocks[Date]))
		formatString: "CHF"\ #,0.###############;"CHF"-#,0.###############;"CHF"\ #,0.###############
		lineageTag: e798791b-a302-41b5-ad35-cfd74ca7dfe5

		annotation PBI_FormatHint = {"currencyCulture":"en-CH"}

	measure 'First Close Price Blank' = CALCULATE(FIRSTNONBLANKVALUE(factStocks[Date],[Total Close Price]),ALLSELECTED(factStocks[Date]))
		formatString: "CHF"\ #,0.###############;"CHF"-#,0.###############;"CHF"\ #,0.###############
		lineageTag: 71fd74e5-3a02-4ea1-902f-f5f8b8670349

		annotation PBI_FormatHint = {"currencyCulture":"en-CH"}

	measure 'Up line' = IF([Last Close Price Blank]>[First Close Price Blank], [Total Close Price], BLANK())
		formatString: "CHF"\ #,0.###############;"CHF"-#,0.###############;"CHF"\ #,0.###############
		lineageTag: f29e95ca-041a-4f4e-9b54-1041659118d9

		annotation PBI_FormatHint = {"currencyCulture":"en-CH"}

	measure 'Down line' = IF([Last Close Price Blank]<[First Close Price Blank], [Total Close Price], BLANK())
		formatString: "CHF"\ #,0.###############;"CHF"-#,0.###############;"CHF"\ #,0.###############
		lineageTag: 42c8d276-e9cb-4859-8dc1-23cab7eba472

		annotation PBI_FormatHint = {"currencyCulture":"en-CH"}

	measure 'SVG_Sparkline with Intersect' = ```
			
			VAR topLineColour = "blue"
			VAR bottomLineColour = "magenta"
			
			// Get the selected period's StartDate and EndDate from dimPeriod
			VAR _SelectedPeriodStart = SELECTEDVALUE(dimPeriod[StartDate])
			VAR _SelectedPeriodEnd = SELECTEDVALUE(dimPeriod[EndDate])
			
			// Calculate the X-axis range based on the selected period (dimPeriod)
			VAR XMinDate = _SelectedPeriodStart
			VAR XMaxDate = _SelectedPeriodEnd
			
			// Calculate the minimum and maximum Y values within the selected date range (factStocks[Date] within the period)
			VAR YMinValue = MINX(
			    FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate),
			    CALCULATE([sumClose])
			)
			VAR YMaxValue = MAXX(
			    FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate),
			    CALCULATE([sumClose])
			)
			
			// Build a table of X & Y coordinates based on the selected period, scaled to fit 50x150 viewbox
			VAR SparklineTable = ADDCOLUMNS(
			    SUMMARIZE(
			        FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate),
			        factStocks[Date]
			    ),
			    "X", INT(150 * DIVIDE(factStocks[Date] - XMinDate, XMaxDate - XMinDate)),  // Scale X based on the selected period
			    "Y", INT(50 * DIVIDE([sumClose] - YMinValue, YMaxValue - YMinValue))  // Scale Y based on the selected period
			)
			
			// Concatenate X & Y coordinates into a polyline for the sparkline
			VAR Lines = CONCATENATEX(SparklineTable, [X] & "," & 50 - [Y], " ", factStocks[Date])
			
			// Calculate the intersection line position based on the selected period's data
			VAR lineIntersection = AVERAGEX(
			    FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate),
			    CALCULATE([sumClose])
			)
			VAR intersectScaled = INT(50 * DIVIDE(lineIntersection - YMinValue, YMaxValue - YMinValue))
			
			// SVG Definitions for styling and markers
			VAR Defs = 
			"<defs>
			    <clipPath id='cut-bottom'>
			      <rect x='0' y='0' width='150' height='" & intersectScaled & "' />
			    </clipPath>
			
			    <marker id='circle' markerWidth='4' markerHeight='4' refX='2' refY='2' >
			      <circle cx='2' cy='2' r='1' fill='steelblue' />
			    </marker>
			
			    <marker id='circleLarge' markerWidth='4' markerHeight='4' refX='2' refY='2' >
			      <circle cx='2' cy='2' r='1.25' fill='red' stroke='black' />
			    </marker>
			
			    <marker id='arrow' markerWidth='3' markerHeight='3' refX='2' refY='2' orient='auto' >
			      <path d='M 0 0 L 10 5 L 0 10 z' fill='black' />
			    </marker>
			</defs>"
			
			// Final SVG construction
			VAR SVGImageURL = 
			    "data:image/svg+xml;utf8," & 
			    "<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-5 -5 160 60' >" & Defs &
			    "<polyline fill='none' stroke='" & bottomLineColour & "' stroke-width='3' points='" & Lines & "' stroke-linecap='round' stroke-linejoin='round' marker-start='url(#circle)' marker-mid='url(#circle)' marker-end='url(#circleLarge)' />" & 
			    "<polyline fill='none' stroke='" & topLineColour & "' stroke-width='3' points='" & Lines & "' stroke-linecap='round' stroke-linejoin='round' clip-path='url(#cut-bottom)' marker-start='url(#circle)' marker-mid='url(#circle)' marker-end='url(#circleLarge)' />" & 
			    "<line x1='0' y1='" & intersectScaled & "' x2='150' y2='" & intersectScaled & "' stroke ='grey' stroke-width ='2' stroke-dasharray='5,5' />" &
			    "</svg>"
			
			RETURN SVGImageURL
			
			```
		lineageTag: a7da3cd0-d12d-417a-abf3-e067d37b6643
		dataCategory: ImageUrl

	measure sumClose =
			
			VAR _Period = SELECTEDVALUE(_tParameter[NbOfDays])
			VAR _LastDate = LASTDATE(factStocks[Date])
			VAR _DatesInPeriod = DATESINPERIOD(factStocks[Date], _LastDate, -_Period, DAY)
			VAR _SelectedPeriodStart = SELECTEDVALUE(dimPeriod[StartDate])
			VAR _SelectedPeriodEnd = SELECTEDVALUE(dimPeriod[EndDate])
			RETURN
			    CALCULATE(
			        SUM(factStocks[Close]),
			        _DatesInPeriod,
			        FILTER(
			            factStocks,
			            factStocks[Date] >= _SelectedPeriodStart &&
			            factStocks[Date] <= _SelectedPeriodEnd
			        ),
			        ALLEXCEPT(dimLogo, dimLogo[Company])  // Ensures calculation happens per company
			    )
		lineageTag: 3830dde8-d634-4d36-96cf-aaea1bd2bfc6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Delta = [LastClosePrice] - [BeginingPeriodPrice]
		formatString: "CHF"\ #,0.###############;"CHF"-#,0.###############;"CHF"\ #,0.###############
		lineageTag: d35dbfa1-7998-4249-bbf7-f1e4eeee22d2

		annotation PBI_FormatHint = {"currencyCulture":"en-CH"}

	measure SVG = ```
			
			    VAR LineColourPositive = "#00A651"  // Green line for positive Delta
			    VAR LineColourNegative = "#FF0000"  // Red line for negative Delta
			    VAR PointColour = "white"            // White points on the line
			
			    // Gradient definitions for positive and negative Delta
			    VAR DefsPositive = "<defs>
			        <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#00A651' offset='0' />
			            <stop stop-color='#00A651' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			    
			    VAR DefsNegative = "<defs>
			        <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#FF0000' offset='0' />
			            <stop stop-color='#FF0000' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			    
			    // Date range for the sparkline (X axis) from the same dataset as the original logic
			    VAR XMinDate = SELECTEDVALUE(dimPeriod[StartDate])  // StartDate from dimPeriod table
			    VAR XMaxDate = SELECTEDVALUE(dimPeriod[EndDate])    // EndDate from dimPeriod table
			    
			    // Calculate overall min and max stock closing values for the selected date range
			    VAR YMinValue = MINX(
			        FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate),
			        CALCULATE([sumClose])
			    )
			    VAR YMaxValue = MAXX(
			        FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate),
			        CALCULATE([sumClose])
			    )
			    
			    // Build table of X & Y coordinates based on the same date range, scaled to the 50 x 150 viewbox
			    VAR SparklineTable = ADDCOLUMNS(
			        SUMMARIZE(
			            FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate),
			            factStocks[Date]
			        ),
			        "X", INT(150 * DIVIDE(factStocks[Date] - XMinDate, XMaxDate - XMinDate)),
			        "Y", INT(50 * DIVIDE([sumClose] - YMinValue, YMaxValue - YMinValue))
			    )
			    
			    // Concatenate X & Y coordinates to form the sparkline line path
			    VAR Lines = CONCATENATEX(SparklineTable, [X] & "," & 50 - [Y], " ", factStocks[Date])
			    
			    // Last data points for highlighting the final point on the sparkline
			    VAR LastSparkYValue = MAXX(FILTER(SparklineTable, factStocks[Date] = XMaxDate), [Y])
			    VAR LastSparkXValue = MAXX(FILTER(SparklineTable, factStocks[Date] = XMaxDate), [X])
			    
			    // Determine whether the Delta is positive or negative and use the corresponding gradient and line color
			    VAR Gradient = IF([Delta] > 0, DefsPositive, DefsNegative)
			    VAR LineColour = IF([Delta] > 0, LineColourPositive, LineColourNegative)
			    
			    // Scale the Moving Average value to fit the 50 x 150 viewbox
			    VAR ReferenceLineScaled = INT(50 * DIVIDE([lineChart_Moving Average] - YMinValue, YMaxValue - YMinValue))
			    
			    // Build the SVG image
			    VAR SVGImageURL = 
			        "data:image/svg+xml;utf8," & 
			        "<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & 
			        Gradient &  // Use the correct gradient definition (green or red)
			        // Opaque area filled with gradient
			        "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' stroke-width='0' points='0,50 " & Lines & " 150,50 Z' />" & 
			        // Line with the defined color and stroke width
			        "<polyline fill='transparent' stroke='" & LineColour & "' stroke-linecap='round' stroke-linejoin='round' stroke-width='3' points='" & Lines & "' />" & 
			        // Last point with the circle to highlight it
			        "<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='3' fill='" & PointColour & "' />" & 
			        // Add the reference line (moving average line) at the calculated position
			        "<line x1='0' y1='" & ReferenceLineScaled & "' x2='150' y2='" & ReferenceLineScaled & "' stroke='grey' stroke-width='2' stroke-dasharray='5,5' />" & 
			        "</svg>"
			    
			    RETURN 
			        SVGImageURL
			
			```
		lineageTag: 018f5a74-c661-4f24-b27e-9ae0e2f700fe
		dataCategory: ImageUrl

	measure tabel_companyNameAndTags =
			
			VAR _Company = MAX(dimLogo[Company])
			VAR _Symbol = MAX(dimMeta[Symbol])
			VAR _Industry = MAX(dimMeta[Industry])
			VAR _Sector = MAX(dimMeta[Sector])
			VAR NewLine = UNICHAR(10)
			
			RETURN
			_Company & NewLine & "🏷️:" & _Sector
		lineageTag: 71d51399-5cd6-425e-b078-646b04cc2c7a

	measure tabel_SVGLineAreaChartTabel = ```
			
			    VAR LineColourPositive = "#00A651"  // Green line for positive Delta
			    VAR LineColourNegative = "#FF0000"  // Red line for negative Delta
			    VAR PointColour = "white"           // White points on the line
			
			    // Gradient definitions for positive and negative Delta
			    VAR DefsPositive = "<defs>
			        <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#00A651' offset='0' />
			            <stop stop-color='#00A651' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			
			    VAR DefsNegative = "<defs>
			        <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#FF0000' offset='0' />
			            <stop stop-color='#FF0000' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			
			    // Date range for the sparkline (X axis) 
			    VAR XMinDate = 
			        IF (
			            ISBLANK(SELECTEDVALUE(dimPeriod[StartDate])), 
			            MIN(factStocks[Date]), 
			            SELECTEDVALUE(dimPeriod[StartDate]) 
			        ) 
			    VAR XMaxDate = CALCULATE(
			        MAX(factStocks[Date]), 
			        factStocks[Date] <= SELECTEDVALUE(dimPeriod[EndDate])
			    )
			
			    // Calculate overall min and max stock closing values for the selected date range
			    VAR YMinValue = MINX(
			        FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate),
			        CALCULATE([sumClose])
			    )
			    VAR YMaxValue = MAXX(
			        FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate),
			        CALCULATE([sumClose])
			    )
			
			    // Build table of X & Y coordinates based on the same date range, scaled to the 60x30 viewbox
			    VAR SparklineTable = ADDCOLUMNS(
			        SUMMARIZE(
			            FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate),
			            factStocks[Date]
			        ),
			        "X", 
			            // Ensure X values start from 0 and adjust for potential rounding errors
			            ROUND(60 * DIVIDE(DATEDIFF(XMinDate, factStocks[Date], DAY), DATEDIFF(XMinDate, XMaxDate, DAY)), 2), 
			        "Y", INT(30 * DIVIDE([sumClose] - YMinValue, YMaxValue - YMinValue))
			    )
			
			    // Concatenate X & Y coordinates to form the sparkline line path
			    VAR Lines = CONCATENATEX(SparklineTable, [X] & "," & 30 - [Y], " ", factStocks[Date])
			
			    // Last data points for highlighting the final point on the sparkline
			    VAR LastSparkYValue = MAXX(FILTER(SparklineTable, factStocks[Date] = XMaxDate), [Y])
			    VAR LastSparkXValue = MAXX(FILTER(SparklineTable, factStocks[Date] = XMaxDate), [X])
			
			    // Determine whether the Delta is positive or negative and use the corresponding gradient and line color
			    VAR Gradient = IF([Delta] > 0, DefsPositive, DefsNegative)
			    VAR LineColour = IF([Delta] > 0, LineColourPositive, LineColourNegative)
			
			    // Scale the Moving Average value to fit the 30x60 viewbox
			    VAR ReferenceLineScaled = INT(30 * DIVIDE([lineChart_Moving Average] - YMinValue, YMaxValue - YMinValue))
			
			    // Build the SVG image
			    VAR SVGImageURL = 
			        "data:image/svg+xml;utf8," & 
			        "<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-4 -4 67 37'>" & 
			        Gradient &  // Use the correct gradient definition (green or red)
			        // Opaque area filled with gradient
			        "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' stroke-width='0' points='0,30 " & Lines & " 60,30 Z' />" & 
			        // Line with the defined color and stroke width
			        "<polyline fill='transparent' stroke='" & LineColour & "' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' points='" & Lines & "' />" & 
			        // Last point with the circle to highlight it
			        "<circle cx='" & LastSparkXValue & "' cy='" & 30 - LastSparkYValue & "' r='2.5' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & 
			        // Add the reference line (moving average line) at the calculated position
			        "<line x1='0' y1='" & ReferenceLineScaled & "' x2='60' y2='" & ReferenceLineScaled & "' stroke='grey' stroke-width='1.5' stroke-dasharray='4,4' />" & 
			        "</svg>"
			
			    RETURN 
			        SVGImageURL
			```
		lineageTag: 59e0d4b2-d73d-40ee-845d-7ad62474ab3c
		dataCategory: ImageUrl

	measure sumClose_Dynamic = [sumClose]
		lineageTag: 919216b5-7bd9-498c-85ba-b8fda88cf385

		formatStringDefinition = ```
				VAR SelectedCurrency = 
				    CALCULATE(
				        SELECTEDVALUE(dimCurrencySymbol[Currency Symbol]),
				        TREATAS(VALUES(dimMeta[Currency]), dimCurrencySymbol[Currency])
				    )
				RETURN
				    "#,0.0#" & " " & SelectedCurrency
				```

	measure selectedCurrencySymbol = ```
			
			    CALCULATE(
			        SELECTEDVALUE(dimCurrencySymbol[Currency Symbol]),
			        TREATAS(VALUES(dimMeta[Currency]), dimCurrencySymbol[Currency])
			    )
			```
		lineageTag: 4af61efb-a953-4ec9-861c-e215cf92e235

	measure tabel_sumClose_Dynamic_Symbol = ```
			
			VAR NewLine = UNICHAR(10)
			VAR _sumClose = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT([sumClose_simple], "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			VAR _Variation = DIVIDE([LastClosePrice], [BeginingPeriodPrice]) - 1
			VAR VariationText = 
			    IF(
			        _Variation > 0,
			        [Variation %],
			        [Variation %]
			    )
			RETURN
			_sumClose & "" & [selectedCurrencySymbol] & NewLine & VariationText
			```
		lineageTag: 4d7d6e7a-320c-4530-81be-d2f81f390ffd

	measure companyNameAndTags_v2 =
			
			VAR _Company = MAX(dimLogo[Company])
			VAR _Symbol = MAX(dimMeta[Symbol])
			VAR _Industry = MAX(dimMeta[Industry])
			VAR _Sector = MAX(dimMeta[Sector])
			VAR _CurrencyName = MAX(dimMeta[Currency])
			VAR _exchangeName = MAX(dimMeta[Exchange Name])
			VAR NewLine =
			"
			"
			RETURN
			"🏷️:" & _Symbol & " | 🪙:" & _CurrencyName & " | 💰:" & _exchangeName
		lineageTag: 07a13af8-3334-4044-867d-59f8ea5c34ed

	measure sumClose_simple = ```
			
			VAR _LastDate = LASTDATE(factStocks[Date])
			RETURN
			    CALCULATE(
			        AVERAGE(factStocks[Close]),
			        factStocks[Date] = _LastDate
			          // Ensures calculation happens per company
			    )
			
			```
		lineageTag: 66e4838e-5942-40d0-8bf9-63448ca65133

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tabel_Rank =
			
			IF(SELECTEDVALUE(_tFilters[Order]) = "ASC",
			RANKX(ALLSELECTED(dimLogo),[Variation], , ASC),
			RANKX(ALLSELECTED(dimLogo),[Variation], , DESC)
			)
		formatString: 0
		lineageTag: c7dc4ddf-d208-4e61-9409-6b5768c4f7f1

	measure Variation = DIVIDE([LastClosePrice], [BeginingPeriodPrice]) - 1
		lineageTag: f91b8c60-c286-441e-af6a-4280daa4c0d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Last Close Price' = ```
			
			VAR _LastDate = LASTDATE(factStocks[Date])
			
			-- Retrieve the currency for the current context
			VAR _Currency = SELECTEDVALUE(dimMeta[Currency])
			
			-- Calculate the last close price
			VAR _LastClose = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(CALCULATE(AVERAGE(factStocks[Close]), factStocks[Date] = _LastDate), "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			
			-- Format the value with the currency symbol and custom separators
			RETURN 
			_LastClose & [selectedCurrencySymbol]
			```
		lineageTag: f1660a84-8746-4053-b0b6-b188ee8b5858

	measure summaryPreviousClosePrice = ```
			
			VAR PrevClose = 
			CALCULATE(
			    AVERAGE(factStocks[PrevClose]),
			    LASTDATE(factStocks[Date])
			)
			VAR PreCloseFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(PrevClose, "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			RETURN
			PreCloseFormated & [selectedCurrencySymbol]
			```
		lineageTag: dbda4284-5b97-459d-a1a9-2211986203f0

	measure summaryLastOpenPrice = ```
			
			VAR OpenPrice = 
			CALCULATE(
			    AVERAGE(factStocks[Open]),
			    LASTDATE(factStocks[Date])
			)
			VAR OpenPriceFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(OpenPrice, "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			RETURN
			OpenPriceFormated & [selectedCurrencySymbol]
			```
		lineageTag: e76470ca-0ac4-4608-99f1-059e0a395b30

	measure summaryLastVolume = ```
			
			VAR Volume = 
			CALCULATE(
			    AVERAGE(factStocks[Volume]),
			    LASTDATE(factStocks[Date])
			)
			VAR VolumeFormated = FORMAT(Volume, "0,,.00M")
			//VAR VolumeFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(Volume, "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			RETURN
			VolumeFormated & [selectedCurrencySymbol]
			```
		lineageTag: 34bfc549-d2a9-464f-b36d-2a27ccd0a43c

	measure summary52WeeksRange = ```
			
			VAR _WeeksRangeLow = 
			CALCULATE(
			    AVERAGE(dimMeta[52 Week Low]),
			    LASTDATE(factStocks[Date])
			)
			VAR _WeeksRangeLowFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(_WeeksRangeLow, "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			VAR _WeeksRangeHigh =
			CALCULATE(
			    AVERAGE(dimMeta[52 Week High]),
			    LASTDATE(factStocks[Date])
			)
			
			VAR _WeeksRangeHighFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(_WeeksRangeHigh, "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			RETURN
			_WeeksRangeLowFormated & [selectedCurrencySymbol] & " - " & _WeeksRangeHighFormated & [selectedCurrencySymbol]
			```
		lineageTag: 8788732f-3a7b-455e-9f79-0e7c7fe149ac

	measure summaryDaysRange = ```
			
			VAR _DaysRangeLow = 
			CALCULATE(
			    AVERAGE(factStocks[Low]),
			    LASTDATE(factStocks[Date])
			)
			VAR _DaysRangeLowFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(_DaysRangeLow, "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			VAR _DaysRangeHigh =
			CALCULATE(
			    AVERAGE(factStocks[High]),
			    LASTDATE(factStocks[Date])
			)
			
			VAR _DaysRangeHighFormated = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(_DaysRangeHigh, "#,0.00;" ), ".", "@" ), ",", "." ), "@", "," )
			RETURN
			_DaysRangeLowFormated & [selectedCurrencySymbol] & " - " & _DaysRangeHighFormated & [selectedCurrencySymbol]
			```
		lineageTag: ddf872ac-580b-4ca7-9627-876cc55dcc1c

	measure portofolio_#1_Company = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])
			
			-- Ensure a company is selected before proceeding
			VAR _HasSelection = ISFILTERED(dimLogo[Company])
			
			VAR _TOP1 = TOPN(1, _SelectedValues, dimLogo[Company], ASC)
			VAR _FirstCompany = MAXX(_TOP1, dimLogo[Company])
			
			-- Get the corresponding symbol for the selected company
			VAR _Symbol = 
			    MAXX(
			        FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			        dimLogo[Symbol]
			    )
			
			VAR NewLine = UNICHAR(10)
			
			RETURN
			    IF(
			        _HasSelection, 
			        _FirstCompany & NewLine & "🏷️: " & _Symbol, 
			        BLANK()
			    )
			
			```
		lineageTag: 62afe595-077a-4a6a-9ce0-d1bc8800535e

	measure portofolio_#1_Symbol = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])
			VAR _FirstCompany = 
			    MAXX(
			        TOPN(1, _SelectedValues, dimLogo[Company], ASC), 
			        dimLogo[Company]
			    )
			VAR _FilteredSymbol = 
			    MAXX(
			        FILTER(dimLogo, dimLogo[Company] = _FirstCompany), 
			        dimLogo[Symbol]
			    )
			RETURN
			    IF(COUNTROWS(_SelectedValues) >= 1, "🏷️: " & _FilteredSymbol, BLANK())
			
			```
		lineageTag: 3d9ea75d-4fdf-485d-9fbd-006bb1c7be40

	measure summarySector = MAX(dimMeta[Sector])
		lineageTag: fcff112a-d220-4717-8c38-bc5d48b58b6a

	measure summaryIndustry = MAX(dimMeta[Industry])
		lineageTag: fc60de9b-1ff9-4554-9767-ac8ea0808073

	measure 'At Close' = ```
			
			VAR _MaxDate = LASTDATE(factStocks[Date])
			VAR NewLine =
			"
			"
			RETURN
			"🕒Closed at " & FORMAT( _MaxDate, "dddd, d mmmm yyyy")
			
			```
		lineageTag: 1c569c2d-9b73-405b-8622-bcda2f268706

	measure portofolio_#1_Period =
			
			VAR _Period = MAX(dimPeriod[Period])
			RETURN
			    "△ Period(" & _Period & ")"
		lineageTag: 2926b76a-d065-4603-b9ae-c57038936ff3

	measure portofolio_#1_LastClosePrice = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])
			VAR _FirstCompany =
			    MAXX(
			        TOPN(1, _SelectedValues, dimLogo[Company], ASC),
			        dimLogo[Company]
			    )
			VAR _FilteredSymbol =
			    MAXX(
			        FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			        dimLogo[Symbol]
			    )
			VAR _FilteredCurrency =
			    MAXX(
			        FILTER(dimMeta, dimMeta[Symbol] = _FilteredSymbol),
			        dimMeta[Currency]
			    )
			VAR selectedCurrencySymbol =
			    MAXX(
			        FILTER(dimCurrencySymbol, dimCurrencySymbol[Currency] = _FilteredCurrency),
			        dimCurrencySymbol[Currency Symbol]
			    )
			VAR _LastDate =
			    CALCULATE(
			        MAX(factStocks[Date]),
			        FILTER(factStocks, factStocks[Symbol] = _FilteredSymbol)
			    )
			VAR _LastClose =
			    SUBSTITUTE(
			        SUBSTITUTE(
			            SUBSTITUTE(
			                FORMAT(
			                    CALCULATE(
			                        AVERAGE(factStocks[Close]),
			                        factStocks[Date] = _LastDate &&
			                        factStocks[Symbol] = _FilteredSymbol
			                    ),
			                    "#,0.00;"
			                ),
			                ".", "@"
			            ),
			            ",", "."
			        ),
			        "@", ","
			    )
			RETURN
			    _LastClose & " " & selectedCurrencySymbol
			
			```
		lineageTag: dd6c79fc-8480-47dc-9522-21653a77b97d

	measure 'portofolio_#1_Variation %' = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])
			VAR _FirstCompany =
			    MAXX(
			        TOPN(1, _SelectedValues, dimLogo[Company], ASC),
			        dimLogo[Company]
			    )
			VAR _FilteredSymbol =
			    MAXX(
			        FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			        dimLogo[Symbol]
			    )
			
			-- BeginingPeriodPrice Calculation
			VAR _StartDate = CALCULATE(MIN(dimPeriod[StartDate]), ALLSELECTED(dimPeriod))
			VAR _Price =
			    CALCULATE(
			        MAX(factStocks[Close]),
			        factStocks[Date] = _StartDate,
			        factStocks[Symbol] = _FilteredSymbol
			    )
			VAR _NextDay =
			    CALCULATE(
			        MIN(factStocks[Date]),
			        factStocks[Date] > _StartDate,
			        factStocks[Symbol] = _FilteredSymbol
			    )
			VAR _AdjustedPrice =
			    CALCULATE(
			        MAX(factStocks[Close]),
			        factStocks[Date] = _NextDay,
			        factStocks[Symbol] = _FilteredSymbol
			    )
			VAR BeginingPeriodPrice = IF(NOT ISBLANK(_Price), _Price, _AdjustedPrice)
			
			-- LastClosePrice Calculation
			VAR _EndDate = CALCULATE(MAX(dimPeriod[EndDate]), ALLSELECTED(dimPeriod))
			VAR _LastDate =
			    MAXX(
			        FILTER(
			            factStocks,
			            factStocks[Date] <= _EndDate && factStocks[Symbol] = _FilteredSymbol
			        ),
			        factStocks[Date]
			    )
			VAR LastClosePrice =
			    IF(
			        ISBLANK(_LastDate),
			        BLANK(),
			        CALCULATE(
			            MAX(factStocks[Close]),
			            factStocks[Date] = _LastDate,
			            factStocks[Symbol] = _FilteredSymbol
			        )
			    )
			
			-- Variation Calculation
			VAR _Variation = (DIVIDE(LastClosePrice, BeginingPeriodPrice) - 1) * 100
			
			-- Format the scaled variation
			VAR _VariationFormat = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(FORMAT(_Variation, "#,0.00;"), ".", "@"), ",", "."), "@", ",")
			
			-- Add the up or down arrow
			VAR _Arrow = IF(_Variation > 0, UNICHAR(129033) & " ", UNICHAR(129035)) & " "
			
			RETURN
			    _Arrow & _VariationFormat & "%"
			
			```
		lineageTag: 3574e7c5-1788-4827-8a54-50a9ad3b8b23

	measure portofolio_#1_VariationIndicator = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])
			VAR _FirstCompany =
			    MAXX(
			        TOPN(1, _SelectedValues, dimLogo[Company], ASC),
			        dimLogo[Company]
			    )
			VAR _FilteredSymbol =
			    MAXX(
			        FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			        dimLogo[Symbol]
			    )
			
			-- BeginingPeriodPrice Calculation
			VAR _StartDate = CALCULATE(MIN(dimPeriod[StartDate]), ALLSELECTED(dimPeriod))
			VAR _Price =
			    CALCULATE(
			        MAX(factStocks[Close]),
			        factStocks[Date] = _StartDate,
			        factStocks[Symbol] = _FilteredSymbol
			    )
			VAR _NextDay =
			    CALCULATE(
			        MIN(factStocks[Date]),
			        factStocks[Date] > _StartDate,
			        factStocks[Symbol] = _FilteredSymbol
			    )
			VAR _AdjustedPrice =
			    CALCULATE(
			        MAX(factStocks[Close]),
			        factStocks[Date] = _NextDay,
			        factStocks[Symbol] = _FilteredSymbol
			    )
			VAR BeginingPeriodPrice = IF(NOT ISBLANK(_Price), _Price, _AdjustedPrice)
			
			-- LastClosePrice Calculation
			VAR _EndDate = CALCULATE(MAX(dimPeriod[EndDate]), ALLSELECTED(dimPeriod))
			VAR _LastDate =
			    MAXX(
			        FILTER(
			            factStocks,
			            factStocks[Date] <= _EndDate && factStocks[Symbol] = _FilteredSymbol
			        ),
			        factStocks[Date]
			    )
			VAR LastClosePrice =
			    IF(
			        ISBLANK(_LastDate),
			        BLANK(),
			        CALCULATE(
			            MAX(factStocks[Close]),
			            factStocks[Date] = _LastDate,
			            factStocks[Symbol] = _FilteredSymbol
			        )
			    )
			
			-- Variation Calculation
			VAR _Variation = DIVIDE(LastClosePrice, BeginingPeriodPrice) - 1
			
			RETURN
			    IF(_Variation >= 0, 0, 1)
			
			```
		formatString: 0
		lineageTag: ebd164e6-1517-472c-9835-19facc1f9064

	measure portofolio_#1_SVG = ```
			
			    VAR LineColourPositive = "#00A651"  // Green line for positive portofolio_#1_SVG_Delta
			    VAR LineColourNegative = "#FF0000"  // Red line for negative portofolio_#1_SVG_Delta
			    VAR PointColour = "white"           // White points on the line
			
			    -- Gradient definitions for positive and negative portofolio_#1_SVG_Delta
			    VAR DefsPositive = "<defs>
			        <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#00A651' offset='0' />
			            <stop stop-color='#00A651' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			
			    VAR DefsNegative = "<defs>
			        <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#FF0000' offset='0' />
			            <stop stop-color='#FF0000' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			
			    -- Check if a company is selected
			    VAR _HasSelection = ISFILTERED(dimLogo[Company])
			    
			    -- Top selected company and symbol logic
			    VAR _SelectedValues = VALUES(dimLogo[Company])
			    VAR _FirstCompany =
			        MAXX(
			            TOPN(1, _SelectedValues, dimLogo[Company], ASC),
			            dimLogo[Company]
			        )
			
			    VAR _FilteredSymbol =
			        MAXX(
			            FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			            dimLogo[Symbol]
			        )
			
			    -- Date range for the sparkline (X axis)
			    VAR XMinDate = 
			        IF (
			            ISBLANK(SELECTEDVALUE(dimPeriod[StartDate])), 
			            MIN(factStocks[Date]), 
			            SELECTEDVALUE(dimPeriod[StartDate]) 
			        ) 
			    VAR XMaxDate = CALCULATE(
			        MAX(factStocks[Date]), 
			        factStocks[Date] <= SELECTEDVALUE(dimPeriod[EndDate])
			    )
			
			    -- Calculate overall min and max stock closing values for the selected date range and symbol
			    VAR YMinValue = MINX(
			        FILTER(
			            factStocks, 
			            factStocks[Date] >= XMinDate && 
			            factStocks[Date] <= XMaxDate && 
			            factStocks[Symbol] = _FilteredSymbol
			        ),
			        [portofolio_#1_SVG_sumClose]  
			    )
			    VAR YMaxValue = MAXX(
			        FILTER(
			            factStocks, 
			            factStocks[Date] >= XMinDate && 
			            factStocks[Date] <= XMaxDate && 
			            factStocks[Symbol] = _FilteredSymbol
			        ),
			        [portofolio_#1_SVG_sumClose]  
			    )
			
			    -- Build table of X & Y coordinates based on the same date range, scaled to the 60x30 viewbox
			    VAR SparklineTable = ADDCOLUMNS(
			        SUMMARIZE(
			            FILTER(
			                factStocks, 
			                factStocks[Date] >= XMinDate && 
			                factStocks[Date] <= XMaxDate && 
			                factStocks[Symbol] = _FilteredSymbol
			            ),
			            factStocks[Date]
			        ),
			        "X", 
			            ROUND(60 * DIVIDE(DATEDIFF(XMinDate, factStocks[Date], DAY), DATEDIFF(XMinDate, XMaxDate, DAY)), 2), 
			        "Y", 
			            INT(30 * DIVIDE([portofolio_#1_SVG_sumClose] - YMinValue, YMaxValue - YMinValue))
			    )
			
			    -- Concatenate X & Y coordinates to form the sparkline line path
			    VAR Lines = CONCATENATEX(SparklineTable, [X] & "," & 30 - [Y], " ", factStocks[Date])
			
			    -- Last data points for highlighting the final point on the sparkline
			    VAR LastSparkYValue = 
			        MAXX(
			            FILTER(SparklineTable, factStocks[Date] = XMaxDate), 
			            [Y]
			        )
			    VAR LastSparkXValue = 
			        MAXX(
			            FILTER(SparklineTable, factStocks[Date] = XMaxDate), 
			            [X]
			        )
			
			    -- Calculate Delta for coloring
			    VAR Delta = [portofolio_#1_SVG_Delta]
			
			    -- Determine whether the portofolio_#1_SVG_Delta is positive or negative and use the corresponding gradient and line color
			    VAR Gradient = IF(Delta > 0, DefsPositive, DefsNegative)
			    VAR LineColour = IF(Delta > 0, LineColourPositive, LineColourNegative)
			
			    -- Scale the Moving Average value to fit the 30x60 viewbox
			    VAR ReferenceLineScaled = INT(30 * DIVIDE([portofolio_#1_SVG_MovingAverage] - YMinValue, YMaxValue - YMinValue))
			
			    -- Build the SVG image
			    VAR SVGImageURL = 
			        "data:image/svg+xml;utf8," & 
			        "<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-4 -4 67 37'>" & 
			        Gradient &  
			        "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' stroke-width='0' points='0,30 " & Lines & " 60,30 Z' />" & 
			        "<polyline fill='transparent' stroke='" & LineColour & "' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' points='" & Lines & "' />" & 
			        "<circle cx='" & LastSparkXValue & "' cy='" & 30 - LastSparkYValue & "' r='2.5' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & 
			        "<line x1='0' y1='" & ReferenceLineScaled & "' x2='60' y2='" & ReferenceLineScaled & "' stroke='grey' stroke-width='1.5' stroke-dasharray='4,4' />" & 
			        "</svg>"
			
			    RETURN 
			        IF(
			            _HasSelection, 
			            SVGImageURL, 
			            BLANK()
			        )
			
			```
		lineageTag: f50e954b-67c8-49a3-9a8e-28447f26f445
		dataCategory: ImageUrl

	measure portofolio_#1_SVG_sumClose = ```
			
			
			VAR _SelectedValues = VALUES(dimLogo[Company])  -- Get the selected companies
			VAR _FirstCompany =
			    IF(
			        COUNTROWS(_SelectedValues) = 0, 
			        BLANK(),  -- Return blank if no companies are selected
			        MAXX(
			            TOPN(1, _SelectedValues, dimLogo[Company], ASC),  -- Select the top company
			            dimLogo[Company]
			        )
			    )
			
			-- Retrieve the symbol for the selected top company
			VAR _FilteredSymbol =
			    IF(
			        NOT ISBLANK(_FirstCompany),
			        CALCULATE(
			            MAX(dimLogo[Symbol]),  -- Get the symbol from dimLogo
			            dimLogo[Company] = _FirstCompany  -- Filter by the selected top company
			        ),
			        BLANK()  -- Return blank if no top company selected
			    )
			
			-- Period and date logic
			VAR _Period = SELECTEDVALUE(_tParameter[NbOfDays])  -- Get the number of days from the parameter
			VAR _LastDate = LASTDATE(factStocks[Date])  -- Get the last date from factStocks
			VAR _DatesInPeriod = DATESINPERIOD(factStocks[Date], _LastDate, -_Period, DAY)  -- Filter dates for the period
			VAR _SelectedPeriodStart = SELECTEDVALUE(dimPeriod[StartDate])  -- Get the start date of the period
			VAR _SelectedPeriodEnd = SELECTEDVALUE(dimPeriod[EndDate])  -- Get the end date of the period
			
			-- Debugging outputs
			VAR DebugDates = _SelectedPeriodStart & " to " & _SelectedPeriodEnd
			VAR DebugSymbol = _FilteredSymbol
			VAR DebugDatesInPeriod = CONCATENATEX(_DatesInPeriod, factStocks[Date], ", ")
			
			-- Debugging for no data situation
			VAR DebugNoData =
			    IF(
			        ISBLANK(_FilteredSymbol),
			        "No symbol found for company: " & _FirstCompany,
			        "Symbol: " & _FilteredSymbol
			    )
			
			-- Calculate the sum of 'Close' prices, filtered by the symbol and the selected date range
			RETURN
			    IF(
			        ISBLANK(_FilteredSymbol), 
			        DebugNoData,  -- Handle no symbol scenario
			        CALCULATE(
			            SUM(factStocks[Close]),  -- Sum of Close prices
			            _DatesInPeriod,  -- Date range filtering
			            FILTER(
			                factStocks, 
			                factStocks[Date] >= _SelectedPeriodStart &&
			                factStocks[Date] <= _SelectedPeriodEnd &&
			                factStocks[Symbol] = _FilteredSymbol  -- Ensure filtering by symbol
			            ),
			            ALLEXCEPT(dimLogo, dimLogo[Company])  -- Ensures calculation is per selected company
			        )
			    )
			
			```
		lineageTag: 313b826d-5169-4cdd-a4d5-db30bd830c67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure portofolio_#1_SVG_Delta = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])
			VAR _FirstCompany =
			    MAXX(
			        TOPN(1, _SelectedValues, dimLogo[Company], ASC),
			        dimLogo[Company]
			    )
			
			-- Find the Symbol for the selected Company (from dimLogo)
			VAR _FilteredSymbol =
			    MAXX(
			        FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			        dimLogo[Symbol]
			    )
			
			-- BeginingOpenPrice Calculation
			VAR _StartDate = CALCULATE(MIN(dimPeriod[StartDate]), ALLSELECTED(dimPeriod))
			VAR _OpeningPrice =
			    CALCULATE(
			        MAX(factStocks[Open]),
			        factStocks[Date] = _StartDate,
			        factStocks[Symbol] = _FilteredSymbol
			    )
			VAR _NextDay =
			    CALCULATE(
			        MIN(factStocks[Date]),
			        factStocks[Date] > _StartDate,
			        factStocks[Symbol] = _FilteredSymbol
			    )
			VAR _AdjustedOpeningPrice =
			    CALCULATE(
			        MAX(factStocks[Open]),
			        factStocks[Date] = _NextDay,
			        factStocks[Symbol] = _FilteredSymbol
			    )
			VAR BeginingOpenPrice = IF(NOT ISBLANK(_OpeningPrice), _OpeningPrice, _AdjustedOpeningPrice)
			
			-- LastClosePrice Calculation
			VAR _EndDate = CALCULATE(MAX(dimPeriod[EndDate]), ALLSELECTED(dimPeriod))
			VAR _LastDate =
			    MAXX(
			        FILTER(
			            factStocks,
			            factStocks[Date] <= _EndDate && factStocks[Symbol] = _FilteredSymbol
			        ),
			        factStocks[Date]
			    )
			VAR LastClosePrice =
			    IF(
			        ISBLANK(_LastDate),
			        BLANK(),
			        CALCULATE(
			            MAX(factStocks[Close]),
			            factStocks[Date] = _LastDate,
			            factStocks[Symbol] = _FilteredSymbol
			        )
			    )
			
			-- Delta Calculation (LastClosePrice - BeginingOpenPrice)
			VAR _Delta = LastClosePrice - BeginingOpenPrice
			
			RETURN
			    _Delta
			
			```
		lineageTag: b961e04e-f234-4265-a5ba-d8f44dc40d09

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure portofolio_#1_SVG_MovingAverage = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])
			VAR _FirstCompany =
			    MAXX(
			        TOPN(1, _SelectedValues, dimLogo[Company], ASC),
			        dimLogo[Company]
			    )
			
			-- Get the Symbol for the selected Company (from dimLogo)
			VAR _FilteredSymbol =
			    MAXX(
			        FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			        dimLogo[Symbol]
			    )
			
			-- Get the period (number of days for the moving average)
			VAR _Period = SELECTEDVALUE(_tParameter[NbOfDays], 10)  -- Default to 10 days if no value selected
			
			-- Get the latest date in the current context
			VAR _MaxDate = LASTDATE(factStocks[Date]) 
			
			-- Calculate the start date of the moving window
			VAR _StartDate = _MaxDate - _Period + 1 
			
			-- Calculate the numerator (sum of closing prices) for the selected company and period
			VAR _Numerator = CALCULATE(
			    SUM(factStocks[Close]), 
			    factStocks[Date] >= _StartDate && factStocks[Date] <= _MaxDate,
			    factStocks[Symbol] = _FilteredSymbol  -- Filter by Symbol for the selected company
			)
			
			-- Calculate the denominator (count of dates) for the selected company and period
			VAR _Denominator = CALCULATE(
			    COUNT(factStocks[Date]), 
			    factStocks[Date] >= _StartDate && factStocks[Date] <= _MaxDate,
			    factStocks[Symbol] = _FilteredSymbol  -- Filter by Symbol for the selected company
			)
			
			-- Return the moving average (sum / count) or blank if no data
			RETURN 
			IF(_Denominator > 0, DIVIDE(_Numerator, _Denominator), BLANK())
			```
		lineageTag: 75d73290-72c2-4bf3-a8b6-94d3791fe9d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure portofolio_#1_SVG_test = ```
			
			VAR LineColourPositive = "#00A651"  // Green line for positive portofolio_#1_SVG_Delta
			VAR LineColourNegative = "#FF0000"  // Red line for negative portofolio_#1_SVG_Delta
			VAR PointColour = "white"           // White points on the line
			
			-- Gradient definitions for positive and negative portofolio_#1_SVG_Delta
			VAR DefsPositive = "<defs>
			    <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			        <stop stop-color='#00A651' offset='0' />
			        <stop stop-color='#00A651' offset='0.3' />
			        <stop stop-color='white' offset='1' />
			    </linearGradient>
			</defs>"
			
			VAR DefsNegative = "<defs>
			    <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			        <stop stop-color='#FF0000' offset='0' />
			        <stop stop-color='#FF0000' offset='0.3' />
			        <stop stop-color='white' offset='1' />
			    </linearGradient>
			</defs>"
			
			-- Use the existing portofolio_#1_Company measure to get the selected company
			VAR _FirstCompany = [portofolio_#1_Company]
			
			-- If no company is selected, return blank
			IF(ISBLANK(_FirstCompany), BLANK(), 
			    -- Get the symbol for the selected company
			    VAR _FilteredSymbol = MAXX(FILTER(dimLogo, dimLogo[Company] = _FirstCompany), dimLogo[Symbol])
			
			    -- Date range for the sparkline (X axis)
			    VAR XMinDate = IF(ISBLANK(SELECTEDVALUE(dimPeriod[StartDate])), MIN(factStocks[Date]), SELECTEDVALUE(dimPeriod[StartDate]))
			    VAR XMaxDate = CALCULATE(MAX(factStocks[Date]), factStocks[Date] <= SELECTEDVALUE(dimPeriod[EndDate]))
			
			    -- Calculate overall min and max stock closing values for the selected date range and symbol
			    VAR YMinValue = MINX(FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate && factStocks[Symbol] = _FilteredSymbol), [portofolio_#1_SVG_sumClose])
			    VAR YMaxValue = MAXX(FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate && factStocks[Symbol] = _FilteredSymbol), [portofolio_#1_SVG_sumClose])
			
			    -- Build table of X & Y coordinates based on the same date range, scaled to the 60x30 viewbox
			    VAR SparklineTable = ADDCOLUMNS(
			        SUMMARIZE(FILTER(factStocks, factStocks[Date] >= XMinDate && factStocks[Date] <= XMaxDate && factStocks[Symbol] = _FilteredSymbol), factStocks[Date]),
			        "X", ROUND(60 * DIVIDE(DATEDIFF(XMinDate, factStocks[Date], DAY), DATEDIFF(XMinDate, XMaxDate, DAY)), 2), 
			        "Y", INT(30 * DIVIDE([portofolio_#1_SVG_sumClose] - YMinValue, YMaxValue - YMinValue))
			    )
			
			    -- Concatenate X & Y coordinates to form the sparkline line path
			    VAR Lines = CONCATENATEX(SparklineTable, [X] & "," & 30 - [Y], " ", factStocks[Date])
			
			    -- Last data points for highlighting the final point on the sparkline
			    VAR LastSparkYValue = MAXX(FILTER(SparklineTable, factStocks[Date] = XMaxDate), [Y])
			    VAR LastSparkXValue = MAXX(FILTER(SparklineTable, factStocks[Date] = XMaxDate), [X])
			
			    -- Calculate Delta for coloring
			    VAR Delta = [portofolio_#1_SVG_Delta]
			
			    -- Determine whether the portofolio_#1_SVG_Delta is positive or negative and use the corresponding gradient and line color
			    VAR Gradient = IF(Delta > 0, DefsPositive, DefsNegative)
			    VAR LineColour = IF(Delta > 0, LineColourPositive, LineColourNegative)
			
			    -- Scale the Moving Average value to fit the 30x60 viewbox
			    VAR ReferenceLineScaled = INT(30 * DIVIDE([portofolio_#1_SVG_MovingAverage] - YMinValue, YMaxValue - YMinValue))
			
			    -- Build the SVG image
			    VAR SVGImageURL = 
			        "data:image/svg+xml;utf8," & 
			        "<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-4 -4 67 37'>" & 
			        Gradient & 
			        "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' stroke-width='0' points='0,30 " & Lines & " 60,30 Z' />" & 
			        "<polyline fill='transparent' stroke='" & LineColour & "' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' points='" & Lines & "' />" & 
			        -- Last point with the circle to highlight it
			        "<circle cx='" & LastSparkXValue & "' cy='" & 30 - LastSparkYValue & "' r='2.5' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & 
			        "<line x1='0' y1='" & ReferenceLineScaled & "' x2='60' y2='" & ReferenceLineScaled & "' stroke='grey' stroke-width='1.5' stroke-dasharray='4,4' />" & 
			        "</svg>"
			
			    RETURN SVGImageURL
			)
			
			
			```
		lineageTag: 7e3eb818-3544-4b48-9c83-65e5185accaa
		dataCategory: ImageUrl

	measure 0_sort = ```
			
			
			VAR FirstCompany = 
			    CALCULATE(MIN('dimLogo'[Company]), ALL('dimLogo'))
			RETURN IF(SELECTEDVALUE('dimLogo'[Company]) = FirstCompany, 1, BLANK())
			
			```
		formatString: 0
		lineageTag: c14af90e-61da-4f5d-a2e8-60157f726412

	measure 0_sumClose_Test = ```
			
			VAR _LastDate = LASTDATE(factStocks[Date])
			RETURN
			    CALCULATE(
			        AVERAGE(factStocks[Close]),
			        factStocks[Date] = _LastDate
			          // Ensures calculation happens per company
			    )
			
			```
		lineageTag: 76b30fbc-ffb7-43db-8c87-991bc6e19338

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure portofolio_#1_CompanyMatch =
			
			VAR _SelectedValues = VALUES(dimLogo[Company])  -- Get the selected companies
			VAR _TOP1 = TOPN(1, _SelectedValues, dimLogo[Company], ASC)  -- Get the top company in ascending order
			VAR _FirstValue = MAXX(_TOP1, dimLogo[Company])  -- Extract the first value
			RETURN
			    _FirstValue
		lineageTag: e589f286-ebbd-4b05-aa0d-a314b3332c68

	measure portofolio_#1_FilterTEST = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])  -- Get the selected companies
			VAR _TOP1 = TOPN(1, _SelectedValues, dimLogo[Company], ASC)  -- Get the top company in ascending order
			VAR _FirstValue = MAXX(_TOP1, dimLogo[Company])  -- Extract the first value
			RETURN
			    IF(
			        _FirstValue = SELECTEDVALUE(dimLogo[Company]),  -- Ensure comparison is made against a single value
			        1,  -- Return 1 if the top company matches the current row
			        0   -- Return 0 otherwise
			    )
			
			```
		formatString: 0
		lineageTag: ec9a5b9f-2bda-4eae-ae63-e69ddae349b7

	measure 0_test = ```
			
			 
			    VAR LineColourPositive = "#00A651"  // Green line for positive portofolio_#1_SVG_Delta
			    VAR LineColourNegative = "#FF0000"  // Red line for negative portofolio_#1_SVG_Delta
			    VAR PointColour = "white"           // White points on the line
			
			    // Gradient definitions for positive and negative portofolio_#1_SVG_Delta
			    VAR DefsPositive = "<defs>
			        <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#00A651' offset='0' />
			            <stop stop-color='#00A651' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			
			    VAR DefsNegative = "<defs>
			        <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#FF0000' offset='0' />
			            <stop stop-color='#FF0000' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			
			    // Top selected company and symbol logic with error handling
			    VAR _SelectedValues = VALUES(dimLogo[Company])
			
			    VAR _FirstCompany = 
			        IF(
			            ISBLANK(_SelectedValues), 
			            BLANK(), -- Handle no selection gracefully
			            MAXX(
			                TOPN(1, _SelectedValues, dimLogo[Company], ASC), 
			                dimLogo[Company]
			            )
			        )
			
			    VAR _FilteredSymbol = 
			        IF(
			            ISBLANK(_FirstCompany), 
			            BLANK(), -- Handle no valid company
			            MAXX(
			                FILTER(dimLogo, dimLogo[Company] = _FirstCompany), 
			                dimLogo[Symbol]
			            )
			        )
			
			    -- Date range for the sparkline (X axis)
			    VAR XMinDate = 
			        IF (
			            ISBLANK(SELECTEDVALUE(dimPeriod[StartDate])), 
			            MIN(factStocks[Date]), 
			            SELECTEDVALUE(dimPeriod[StartDate]) 
			        ) 
			    VAR XMaxDate = CALCULATE(
			        MAX(factStocks[Date]), 
			        factStocks[Date] <= SELECTEDVALUE(dimPeriod[EndDate])
			    )
			
			    -- Calculate overall min and max stock closing values for the selected date range and symbol
			    VAR YMinValue = MINX(
			        FILTER(
			            factStocks, 
			            factStocks[Date] >= XMinDate && 
			            factStocks[Date] <= XMaxDate && 
			            factStocks[Symbol] = _FilteredSymbol
			        ),
			        [portofolio_#1_SVG_sumClose]  
			    )
			    VAR YMaxValue = MAXX(
			        FILTER(
			            factStocks, 
			            factStocks[Date] >= XMinDate && 
			            factStocks[Date] <= XMaxDate && 
			            factStocks[Symbol] = _FilteredSymbol
			        ),
			        [portofolio_#1_SVG_sumClose]  
			    )
			
			    -- Build table of X & Y coordinates based on the same date range, scaled to the 60x30 viewbox
			    VAR SparklineTable = ADDCOLUMNS(
			        SUMMARIZE(
			            FILTER(
			                factStocks, 
			                factStocks[Date] >= XMinDate && 
			                factStocks[Date] <= XMaxDate && 
			                factStocks[Symbol] = _FilteredSymbol
			            ),
			            factStocks[Date]
			        ),
			        "X", 
			            ROUND(60 * DIVIDE(DATEDIFF(XMinDate, factStocks[Date], DAY), DATEDIFF(XMinDate, XMaxDate, DAY)), 2), 
			        "Y", 
			            INT(30 * DIVIDE([portofolio_#1_SVG_sumClose] - YMinValue, YMaxValue - YMinValue))
			    )
			
			    -- Concatenate X & Y coordinates to form the sparkline line path
			    VAR Lines = CONCATENATEX(SparklineTable, [X] & "," & 30 - [Y], " ", factStocks[Date])
			
			    -- Last data points for highlighting the final point on the sparkline
			    VAR LastSparkYValue = 
			        MAXX(
			            FILTER(SparklineTable, factStocks[Date] = XMaxDate), 
			            [Y]
			        )
			    VAR LastSparkXValue = 
			        MAXX(
			            FILTER(SparklineTable, factStocks[Date] = XMaxDate), 
			            [X]
			        )
			
			    -- Calculate Delta for coloring
			    VAR Delta = [portofolio_#1_SVG_Delta]
			
			    -- Determine whether the portofolio_#1_SVG_Delta is positive or negative and use the corresponding gradient and line color
			    VAR Gradient = IF(Delta > 0, DefsPositive, DefsNegative)
			    VAR LineColour = IF(Delta > 0, LineColourPositive, LineColourNegative)
			
			    -- Scale the Moving Average value to fit the 30x60 viewbox
			    VAR ReferenceLineScaled = INT(30 * DIVIDE([portofolio_#1_SVG_MovingAverage] - YMinValue, YMaxValue - YMinValue))
			
			    -- Build the SVG image
			    VAR SVGImageURL = 
			        "data:image/svg+xml;utf8," & 
			        "<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-4 -4 67 37'>" & 
			        Gradient & 
			        "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' stroke-width='0' points='0,30 " & Lines & " 60,30 Z' />" & 
			        "<polyline fill='transparent' stroke='" & LineColour & "' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' points='" & Lines & "' />" & 
			        "<circle cx='" & LastSparkXValue & "' cy='" & 30 - LastSparkYValue & "' r='2.5' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & 
			        "<line x1='0' y1='" & ReferenceLineScaled & "' x2='60' y2='" & ReferenceLineScaled & "' stroke='grey' stroke-width='1.5' stroke-dasharray='4,4' />" & 
			        "</svg>"
			
			    RETURN 
			        SVGImageURL
			
			```
		lineageTag: 5f5d57d7-2b42-4030-9439-38cc3d7d3ac3
		dataCategory: ImageUrl

	measure 0_test_1 = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])  -- Get all selected companies as a table
			VAR _TopCompany = 
			    IF(
			        COUNTROWS(_SelectedValues) = 0, 
			        BLANK(),  -- Handle the case where no company is selected
			        MAXX(
			            TOPN(1, _SelectedValues, dimLogo[Company], ASC),  -- Get the top company
			            dimLogo[Company]
			        )
			    )
			RETURN 
			    _TopCompany
			
			```
		lineageTag: 91e0b3fb-b05a-42cc-afda-2c133d3d83a4

	measure 0_0_svg = ```
			
			
			    VAR LineColourPositive = "#00A651"  // Green line for positive portofolio_#1_SVG_Delta
			    VAR LineColourNegative = "#FF0000"  // Red line for negative portofolio_#1_SVG_Delta
			    VAR PointColour = "white"           // White points on the line
			
			    // Gradient definitions for positive and negative portofolio_#1_SVG_Delta
			    VAR DefsPositive = "<defs>
			        <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#00A651' offset='0' />
			            <stop stop-color='#00A651' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			
			    VAR DefsNegative = "<defs>
			        <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#FF0000' offset='0' />
			            <stop stop-color='#FF0000' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			
			    -- Top selected company and symbol logic
			    VAR _SelectedValues = VALUES(dimLogo[Company])  -- Get all selected companies as a table
			    VAR _FirstCompany = 
			        IF(
			            COUNTROWS(_SelectedValues) = 0, 
			            BLANK(),  -- Return blank if no companies are selected
			            MAXX(
			                TOPN(1, _SelectedValues, dimLogo[Company], ASC),  -- Get the top company alphabetically
			                dimLogo[Company]
			            )
			        )
			
			    VAR _FilteredSymbol =
			        IF(
			            NOT ISBLANK(_FirstCompany),
			            MAXX(
			                FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			                dimLogo[Symbol]
			            ),
			            BLANK()  -- If no company selected, return blank
			        )
			
			    -- Date range for the sparkline (X axis)
			    VAR XMinDate = 
			        IF (
			            ISBLANK(SELECTEDVALUE(dimPeriod[StartDate])), 
			            MIN(factStocks[Date]), 
			            SELECTEDVALUE(dimPeriod[StartDate]) 
			        ) 
			    VAR XMaxDate = CALCULATE(
			        MAX(factStocks[Date]), 
			        factStocks[Date] <= SELECTEDVALUE(dimPeriod[EndDate])
			    )
			
			    -- Calculate overall min and max stock closing values for the selected date range and symbol
			    VAR YMinValue = MINX(
			        FILTER(
			            factStocks, 
			            factStocks[Date] >= XMinDate && 
			            factStocks[Date] <= XMaxDate && 
			            factStocks[Symbol] = _FilteredSymbol
			        ),
			        [portofolio_#1_SVG_sumClose]  -- Ensure sumClose is used consistently
			    )
			    VAR YMaxValue = MAXX(
			        FILTER(
			            factStocks, 
			            factStocks[Date] >= XMinDate && 
			            factStocks[Date] <= XMaxDate && 
			            factStocks[Symbol] = _FilteredSymbol
			        ),
			        [portofolio_#1_SVG_sumClose]  -- Ensure sumClose is used consistently
			    )
			
			    -- Build table of X & Y coordinates based on the same date range, scaled to the 60x30 viewbox
			    VAR SparklineTable = ADDCOLUMNS(
			        SUMMARIZE(
			            FILTER(
			                factStocks, 
			                factStocks[Date] >= XMinDate && 
			                factStocks[Date] <= XMaxDate && 
			                factStocks[Symbol] = _FilteredSymbol
			            ),
			            factStocks[Date]
			        ),
			        "X", 
			            -- Ensure X values start from 0 and adjust for potential rounding errors
			            ROUND(60 * DIVIDE(DATEDIFF(XMinDate, factStocks[Date], DAY), DATEDIFF(XMinDate, XMaxDate, DAY)), 2), 
			        "Y", 
			            -- Calculate Y values with the proper sumClose context
			            INT(30 * DIVIDE([portofolio_#1_SVG_sumClose] - YMinValue, YMaxValue - YMinValue))
			    )
			
			    -- Concatenate X & Y coordinates to form the sparkline line path
			    VAR Lines = CONCATENATEX(SparklineTable, [X] & "," & 30 - [Y], " ", factStocks[Date])
			
			    -- Last data points for highlighting the final point on the sparkline
			    VAR LastSparkYValue = 
			        MAXX(
			            FILTER(SparklineTable, factStocks[Date] = XMaxDate), 
			            [Y]
			        )
			    VAR LastSparkXValue = 
			        MAXX(
			            FILTER(SparklineTable, factStocks[Date] = XMaxDate), 
			            [X]
			        )
			
			    -- Calculate Delta for coloring
			    VAR Delta = [portofolio_#1_SVG_Delta]
			
			    -- Determine whether the portofolio_#1_SVG_Delta is positive or negative and use the corresponding gradient and line color
			    VAR Gradient = IF(Delta > 0, DefsPositive, DefsNegative)
			    VAR LineColour = IF(Delta > 0, LineColourPositive, LineColourNegative)
			
			    -- Scale the Moving Average value to fit the 30x60 viewbox
			    VAR ReferenceLineScaled = INT(30 * DIVIDE([portofolio_#1_SVG_MovingAverage] - YMinValue, YMaxValue - YMinValue))
			
			    -- Build the SVG image
			    VAR SVGImageURL = 
			        "data:image/svg+xml;utf8," & 
			        "<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-4 -4 67 37'>" & 
			        Gradient &  -- Use the correct gradient definition (green or red)
			        -- Opaque area filled with gradient
			        "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' stroke-width='0' points='0,30 " & Lines & " 60,30 Z' />" & 
			        -- Line with the defined color and stroke width
			        "<polyline fill='transparent' stroke='" & LineColour & "' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' points='" & Lines & "' />" & 
			        -- Last point with the circle to highlight it
			        "<circle cx='" & LastSparkXValue & "' cy='" & 30 - LastSparkYValue & "' r='2.5' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & 
			        -- Add the reference line (moving average line) at the calculated position
			        "<line x1='0' y1='" & ReferenceLineScaled & "' x2='60' y2='" & ReferenceLineScaled & "' stroke='grey' stroke-width='1.5' stroke-dasharray='4,4' />" & 
			        "</svg>"
			
			    RETURN 
			        SVGImageURL
			
			```
		lineageTag: 3034e1af-371c-4709-bd34-190ddd32596f
		dataCategory: ImageUrl

	measure 0_portofolio_#1_LastClosePrice = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])
			VAR _FirstCompany = 
			    IF(
			        COUNTROWS(_SelectedValues) = 0, 
			        BLANK(), 
			        MAXX(
			            TOPN(1, _SelectedValues, dimLogo[Company], ASC),
			            dimLogo[Company]
			        )
			    )
			VAR _FilteredSymbol = 
			    IF(
			        ISBLANK(_FirstCompany),
			        BLANK(),
			        MAXX(
			            FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			            dimLogo[Symbol]
			        )
			    )
			VAR _LastDate =
			    IF(
			        ISBLANK(_FilteredSymbol),
			        BLANK(),
			        CALCULATE(
			            MAX(factStocks[Date]),
			            factStocks[Symbol] = _FilteredSymbol
			        )
			    )
			VAR _LastClose =
			    IF(
			        ISBLANK(_LastDate),
			        BLANK(),
			        CALCULATE(
			            AVERAGE(factStocks[Close]),
			            factStocks[Date] = _LastDate &&
			            factStocks[Symbol] = _FilteredSymbol
			        )
			    )
			RETURN 
			    _LastClose
			
			
			// VAR _SelectedValues = VALUES(dimLogo[Company])
			// VAR _FirstCompany =
			//     MAXX(
			//         TOPN(1, _SelectedValues, dimLogo[Company], ASC),
			//         dimLogo[Company]
			//     )
			// VAR _FilteredSymbol =
			//     MAXX(
			//         FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			//         dimLogo[Symbol]
			//     )
			// VAR _FilteredCurrency =
			//     MAXX(
			//         FILTER(dimMeta, dimMeta[Symbol] = _FilteredSymbol),
			//         dimMeta[Symbol]
			//     )
			
			// VAR _LastDate =
			//     CALCULATE(
			//         MAX(factStocks[Date]),
			//         FILTER(factStocks, factStocks[Symbol] = _FilteredSymbol)
			//     )
			// VAR _LastClose =
			//     CALCULATE(
			//                         AVERAGE(factStocks[Close]),
			//                         factStocks[Date] = _LastDate &&
			//                         factStocks[Symbol] = _FilteredSymbol
			//                     )
			// RETURN
			//     _LastClose
			```
		lineageTag: b621d660-2b09-4349-846c-31c18841a43a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 0_0_portofolio_#1_SVG = ```
			
			    VAR LineColourPositive = "#00A651"  // Green line for positive portofolio_#1_SVG_Delta
			    VAR LineColourNegative = "#FF0000"  // Red line for negative portofolio_#1_SVG_Delta
			    VAR PointColour = "white"           // White points on the line
			
			    // Gradient definitions for positive and negative portofolio_#1_SVG_Delta
			    VAR DefsPositive = "<defs>
			        <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#00A651' offset='0' />
			            <stop stop-color='#00A651' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			
			    VAR DefsNegative = "<defs>
			        <linearGradient id='grad' x1='0' y1='22.5' x2='0' y2='45' gradientUnits='userSpaceOnUse'>
			            <stop stop-color='#FF0000' offset='0' />
			            <stop stop-color='#FF0000' offset='0.3' />
			            <stop stop-color='white' offset='1' />
			        </linearGradient>
			    </defs>"
			
			    -- Top selected company and symbol logic
			    VAR _SelectedValues = VALUES(dimLogo[Company])
			    VAR _FirstCompany =
			        MAXX(
			            TOPN(1, _SelectedValues, dimLogo[Company], ASC),
			            dimLogo[Company]
			        )
			
			    VAR _FilteredSymbol =
			        MAXX(
			            FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			            dimLogo[Symbol]
			        )
			
			    -- Date range for the sparkline (X axis)
			    VAR XMinDate = 
			        IF (
			            ISBLANK(SELECTEDVALUE(dimPeriod[StartDate])), 
			            MIN(factStocks[Date]), 
			            SELECTEDVALUE(dimPeriod[StartDate]) 
			        ) 
			    VAR XMaxDate = CALCULATE(
			        MAX(factStocks[Date]), 
			        factStocks[Date] <= SELECTEDVALUE(dimPeriod[EndDate])
			    )
			
			    -- Calculate overall min and max stock closing values for the selected date range and symbol
			    VAR YMinValue = MINX(
			        FILTER(
			            factStocks, 
			            factStocks[Date] >= XMinDate && 
			            factStocks[Date] <= XMaxDate && 
			            factStocks[Symbol] = _FilteredSymbol
			        ),
			        [0_portofolio_#1_LastClosePrice]  -- Ensure sumClose is used consistently
			    )
			    VAR YMaxValue = MAXX(
			        FILTER(
			            factStocks, 
			            factStocks[Date] >= XMinDate && 
			            factStocks[Date] <= XMaxDate && 
			            factStocks[Symbol] = _FilteredSymbol
			        ),
			        [0_portofolio_#1_LastClosePrice]  -- Ensure sumClose is used consistently
			    )
			
			    -- Build table of X & Y coordinates based on the same date range, scaled to the 60x30 viewbox
			    VAR SparklineTable = ADDCOLUMNS(
			        SUMMARIZE(
			            FILTER(
			                factStocks, 
			                factStocks[Date] >= XMinDate && 
			                factStocks[Date] <= XMaxDate && 
			                factStocks[Symbol] = _FilteredSymbol
			            ),
			            factStocks[Date]
			        ),
			        "X", 
			            -- Ensure X values start from 0 and adjust for potential rounding errors
			            ROUND(60 * DIVIDE(DATEDIFF(XMinDate, factStocks[Date], DAY), DATEDIFF(XMinDate, XMaxDate, DAY)), 2), 
			        "Y", 
			            -- Calculate Y values with the proper sumClose context
			            INT(30 * DIVIDE([0_portofolio_#1_LastClosePrice] - YMinValue, YMaxValue - YMinValue))
			    )
			
			    -- Concatenate X & Y coordinates to form the sparkline line path
			    VAR Lines = CONCATENATEX(SparklineTable, [X] & "," & 30 - [Y], " ", factStocks[Date])
			
			    -- Last data points for highlighting the final point on the sparkline
			    VAR LastSparkYValue = 
			        MAXX(
			            FILTER(SparklineTable, factStocks[Date] = XMaxDate), 
			            [Y]
			        )
			    VAR LastSparkXValue = 
			        MAXX(
			            FILTER(SparklineTable, factStocks[Date] = XMaxDate), 
			            [X]
			        )
			
			    -- Calculate Delta for coloring
			    VAR Delta = [portofolio_#1_SVG_Delta]
			
			    -- Determine whether the portofolio_#1_SVG_Delta is positive or negative and use the corresponding gradient and line color
			    VAR Gradient = IF(Delta > 0, DefsPositive, DefsNegative)
			    VAR LineColour = IF(Delta > 0, LineColourPositive, LineColourNegative)
			
			    -- Scale the Moving Average value to fit the 30x60 viewbox
			    VAR ReferenceLineScaled = INT(30 * DIVIDE([portofolio_#1_SVG_MovingAverage] - YMinValue, YMaxValue - YMinValue))
			
			    -- Build the SVG image
			    VAR SVGImageURL = 
			        "data:image/svg+xml;utf8," & 
			        "<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-4 -4 67 37'>" & 
			        Gradient &  -- Use the correct gradient definition (green or red)
			        -- Opaque area filled with gradient
			        "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' stroke-width='0' points='0,30 " & Lines & " 60,30 Z' />" & 
			        -- Line with the defined color and stroke width
			        "<polyline fill='transparent' stroke='" & LineColour & "' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' points='" & Lines & "' />" & 
			        -- Last point with the circle to highlight it
			        "<circle cx='" & LastSparkXValue & "' cy='" & 30 - LastSparkYValue & "' r='2.5' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & 
			        -- Add the reference line (moving average line) at the calculated position
			        "<line x1='0' y1='" & ReferenceLineScaled & "' x2='60' y2='" & ReferenceLineScaled & "' stroke='grey' stroke-width='1.5' stroke-dasharray='4,4' />" & 
			        "</svg>"
			
			    RETURN 
			        SVGImageURL
			
			```
		lineageTag: b62450ed-d65f-4698-a4f6-23e9f6e6a9a3
		dataCategory: ImageUrl

	measure portofolio_#1_Logo = ```
			
			VAR _SelectedValues = VALUES(dimLogo[Company])
			
			-- Ensure a company is selected before proceeding
			VAR _HasSelection = ISFILTERED(dimLogo[Company])
			
			VAR _TOP1 = TOPN(1, _SelectedValues, dimLogo[Company], ASC)
			VAR _FirstCompany = MAXX(_TOP1, dimLogo[Company])
			
			-- Get the corresponding logo for the selected company
			VAR _Logo = 
			    MAXX(
			        FILTER(dimLogo, dimLogo[Company] = _FirstCompany),
			        dimLogo[Logo]
			    )
			
			RETURN
			    IF(
			        _HasSelection, 
			        _Logo, 
			        BLANK()
			    )
			
			```
		lineageTag: 227d2db9-97e7-4bc5-985e-993932065f6d
		dataCategory: ImageUrl

	measure '0_0_Text Measure' =
			
			// svg essentials
			    var svg_start = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'>"
			    var svg_end = "</svg>"
			    VAR _company = MAX(dimLogo[Company])
			    VAR _symbol = MAX(dimLogo[Symbol])
			// text element including a style tag
			    var svg_text1 ="<text x='50' y='20' style='font:normal 20px sans-serif;' text-anchor='start'>" & _company & "</text>"
			    var svg_text2 ="<text x='50' y='50' style='font:normal 20px sans-serif;' text-anchor='middle'>" & _symbol & "</text>"
			return
			    svg_start & svg_text1 & svg_text2 & svg_end
		lineageTag: 36a88d8d-79e7-48d2-940d-20c4327ac87d
		dataCategory: ImageUrl

	column _Blank
		formatString: 0
		lineageTag: a889a677-a184-452c-9ab3-1dbdcb601569
		summarizeBy: sum
		isNameInferred
		sourceColumn: [_Blank]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = Row("_Blank", BLANK())

	annotation PBI_Id = d3fe511137dc4693a1ba9c24c6d6306b

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

