DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"3M"}, 'dimLogo'[Company])

	VAR __DS0FilterTable2 = 
		TREATAS({"3M"}, 'dimPeriod'[Period])

	VAR __DS0FilterTable3 = 
		TREATAS({"20D"}, '_tParameter'[PeriodName])

	VAR __ValueFilterDM0 = 
		FILTER(
			KEEPFILTERS(
				SUMMARIZECOLUMNS(
					'factStocks'[Date],
					__DS0FilterTable,
					__DS0FilterTable2,
					__DS0FilterTable3,
					"Low", '_Measures'[Low],
					"LowDistance", '_Measures'[LowDistance],
					"BearishCandle", '_Measures'[BearishCandle],
					"BullishCandle", '_Measures'[BullishCandle],
					"High", '_Measures'[High],
					"Moving_Average", '_Measures'[Moving Average],
					"Lower_Band", '_Measures'[Lower Band],
					"Upper_Band", '_Measures'[Upper Band],
					"HighDistance", IGNORE('_Measures'[HighDistance]),
					"DateFilter", IGNORE('_Measures'[DateFilter])
				)
			),
			[DateFilter] = 1
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'factStocks'[Date],
			__DS0FilterTable,
			__DS0FilterTable2,
			__DS0FilterTable3,
			__ValueFilterDM0,
			"Low", '_Measures'[Low],
			"LowDistance", '_Measures'[LowDistance],
			"BearishCandle", '_Measures'[BearishCandle],
			"BullishCandle", '_Measures'[BullishCandle],
			"High", '_Measures'[High],
			"Moving_Average", '_Measures'[Moving Average],
			"Lower_Band", '_Measures'[Lower Band],
			"Upper_Band", '_Measures'[Upper Band],
			"HighDistance", IGNORE('_Measures'[HighDistance])
		)

	VAR __DS0BodyLimited = 
		SAMPLE(3502, __DS0Core, 'factStocks'[Date], 1)

EVALUATE
	SUMMARIZECOLUMNS(
		__DS0FilterTable,
		__DS0FilterTable2,
		__DS0FilterTable3,
		__ValueFilterDM0,
		"MinY", IGNORE('_Measures'[MinY]),
		"MaxY", IGNORE('_Measures'[MaxY])
	)

EVALUATE
	__DS0BodyLimited

ORDER BY
	'factStocks'[Date]